const key='absensi_siswa_v1';let data=JSON.parse(localStorage.getItem(key)||'[]');
const date=document.querySelector('#date'),student=document.querySelector('#student'),className=document.querySelector('#className'),schoolName=document.querySelector('#schoolName'),teacherName=document.querySelector('#teacherName'),status=document.querySelector('#status'),rows=document.querySelector('#rows'),summary=document.querySelector('#summary'),filterDate=document.querySelector('#filterDate'),filterClass=document.querySelector('#filterClass'),filterStatus=document.querySelector('#filterStatus');
date.value=new Date().toISOString().slice(0,10);schoolName.value=localStorage.getItem('school_name')||'';teacherName.value=localStorage.getItem('teacher_name')||'';
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function save(){localStorage.setItem(key,JSON.stringify(data));localStorage.setItem('school_name',schoolName.value.trim());localStorage.setItem('teacher_name',teacherName.value.trim());render()}
function filteredData(){const d=filterDate.value,c=filterClass.value.trim().toLowerCase(),s=filterStatus.value;return data.filter(x=>(!d||x.date===d)&&(!c||x.className.toLowerCase()===c)&&(!s||x.status===s))}
function render(){const filtered=filteredData();rows.innerHTML='';document.querySelector('#empty').style.display=filtered.length?'none':'block';filtered.forEach((x,i)=>{const original=data.indexOf(x);const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${esc(x.student)}</td><td>${esc(x.className)}</td><td>${x.date}</td><td><span class="pill pill-${x.status.toLowerCase()}">${x.status}</span></td><td><button class="del" onclick="removeItem(${original})">Hapus</button></td>`;rows.appendChild(tr)});const c={Hadir:0,Izin:0,Sakit:0,Alpa:0};filtered.forEach(x=>c[x.status]++);summary.innerHTML=`<span class="badge">Total: ${filtered.length}</span>`+Object.entries(c).map(([k,v])=>`<span class="badge">${k}: ${v}</span>`).join('');updateDashboard()}
function updateDashboard(){const c={Hadir:0,Izin:0,Sakit:0,Alpa:0};data.forEach(x=>c[x.status]++);const total=data.length;document.querySelector('#totalStat').textContent=total;document.querySelector('#hadirStat').textContent=c.Hadir;document.querySelector('#izinStat').textContent=c.Izin;document.querySelector('#sakitStat').textContent=c.Sakit;document.querySelector('#alpaStat').textContent=c.Alpa;const pct=total?Math.round(c.Hadir/total*100):0;document.querySelector('#percentStat').textContent=pct+'%';document.querySelector('#progressBar').style.width=pct+'%';const max=Math.max(1,...Object.values(c));document.querySelector('#chart').innerHTML=Object.entries(c).map(([k,v])=>`<div class="bar-wrap"><span class="bar-value">${v}</span><div class="bar" style="height:${Math.max(3,v/max*130)}px"></div><span class="bar-label">${k}</span></div>`).join('');const recent=[...data].slice(-5).reverse();document.querySelector('#recent').innerHTML=recent.length?recent.map(x=>`<div class="recent-item"><div><div class="recent-name">${esc(x.student)}</div><div class="recent-meta">${esc(x.className)} · ${x.date}</div></div><span class="pill pill-${x.status.toLowerCase()}">${x.status}</span></div>`).join(''):'<p class="empty">Belum ada data absensi.</p>'}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));document.querySelector('#'+page).classList.add('active-page');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('#navlinks').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(page==='rekap')render()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelector('#menuBtn').onclick=()=>document.querySelector('#navlinks').classList.toggle('open');document.querySelector('#add').onclick=()=>{if(!student.value.trim()||!className.value.trim()||!date.value)return alert('Isi tanggal, nama siswa, dan kelas terlebih dahulu.');data.push({student:student.value.trim(),className:className.value.trim(),date:date.value,status:status.value});student.value='';save();showPage('dashboard')};window.removeItem=i=>{if(confirm('Hapus data ini?')){data.splice(i,1);save()}};document.querySelector('#clear').onclick=()=>{if(confirm('Hapus seluruh data absensi?')){data=[];save()}};
[filterDate,filterClass,filterStatus].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));
document.querySelector('#export').onclick=()=>{const filtered=filteredData();if(!filtered.length)return alert('Tidak ada data sesuai filter.');const {jsPDF}=window.jspdf;const sekolah=schoolName.value.trim()||'Nama Sekolah',guru=teacherName.value.trim()||'Nama Guru',kelas=filterClass.value.trim()||'Semua Kelas',tanggal=filterDate.value?new Date(filterDate.value+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'}):'Semua Tanggal';const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(16);doc.text(sekolah,148,12,{align:'center'});doc.setFontSize(13);doc.text('REKAP ABSENSI SISWA',148,19,{align:'center'});doc.setFontSize(10);doc.text(`Kelas: ${kelas}    |    Tanggal: ${tanggal}`,148,26,{align:'center'});const counts={Hadir:0,Izin:0,Sakit:0,Alpa:0};filtered.forEach(x=>counts[x.status]++);doc.autoTable({startY:32,head:[['No','Nama Siswa','Kelas','Tanggal','Status']],body:filtered.map((x,i)=>[i+1,x.student,x.className,new Date(x.date+'T00:00:00').toLocaleDateString('id-ID'),x.status]),styles:{fontSize:9,cellPadding:3},headStyles:{fontStyle:'bold'},margin:{left:12,right:12}});let y=doc.lastAutoTable.finalY+8;doc.setFontSize(10);doc.text(`Jumlah: Hadir ${counts.Hadir} | Izin ${counts.Izin} | Sakit ${counts.Sakit} | Alpa ${counts.Alpa}`,12,y);doc.text(`Dicetak: ${new Date().toLocaleString('id-ID')}`,12,y+6);doc.text('Mengetahui,',225,y+8,{align:'center'});doc.text('Guru / Wali Kelas',225,y+14,{align:'center'});doc.text(guru,225,y+34,{align:'center'});doc.line(190,y+36,260,y+36);doc.save(`rekap-absensi-${(kelas||'semua-kelas').replace(/\s+/g,'-')}-${filterDate.value||'semua-tanggal'}.pdf`)};
schoolName.addEventListener('change',save);teacherName.addEventListener('change',save);document.querySelector('#todayLabel').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});render();