const key='absensi_siswa_v1',studentKey='siswa_v1',sessionKey='sias_session';
let data=JSON.parse(localStorage.getItem(key)||'[]'),students=JSON.parse(localStorage.getItem(studentKey)||'[]'),role='guru';
const $=s=>document.querySelector(s);
const date=$('#date'),student=$('#student'),className=$('#className'),schoolName=$('#schoolName'),teacherName=$('#teacherName'),status=$('#status'),rows=$('#rows'),summary=$('#summary'),filterDate=$('#filterDate'),filterClass=$('#filterClass'),filterStatus=$('#filterStatus');
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function persist(){localStorage.setItem(key,JSON.stringify(data));localStorage.setItem(studentKey,JSON.stringify(students));localStorage.setItem('school_name',schoolName.value.trim());localStorage.setItem('teacher_name',teacherName.value.trim());render();renderStudents();populateLists()}
function filteredData(){const d=filterDate.value,c=filterClass.value.trim().toLowerCase(),s=filterStatus.value;return data.filter(x=>(!d||x.date===d)&&(!c||x.className.toLowerCase()===c)&&(!s||x.status===s))}
function render(){const filtered=filteredData();rows.innerHTML='';$('#empty').style.display=filtered.length?'none':'block';filtered.forEach((x,i)=>{const original=data.indexOf(x),tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${esc(x.student)}</td><td>${esc(x.className)}</td><td>${x.date}</td><td><span class="pill pill-${x.status.toLowerCase()}">${x.status}</span></td><td>${role==='guru'?`<button class="del" onclick="removeItem(${original})">Hapus</button>`:'-'}</td>`;rows.appendChild(tr)});const c={Hadir:0,Izin:0,Sakit:0,Alpa:0};filtered.forEach(x=>c[x.status]++);summary.innerHTML=`<span class="badge">Total: ${filtered.length}</span>`+Object.entries(c).map(([k,v])=>`<span class="badge">${k}: ${v}</span>`).join('');updateDashboard()}
function updateDashboard(){const c={Hadir:0,Izin:0,Sakit:0,Alpa:0};data.forEach(x=>c[x.status]++);const total=data.length;$('#totalStat').textContent=total;$('#hadirStat').textContent=c.Hadir;$('#izinStat').textContent=c.Izin;$('#sakitStat').textContent=c.Sakit;$('#alpaStat').textContent=c.Alpa;const pct=total?Math.round(c.Hadir/total*100):0;$('#percentStat').textContent=pct+'%';$('#progressBar').style.width=pct+'%';const max=Math.max(1,...Object.values(c));$('#chart').innerHTML=Object.entries(c).map(([k,v])=>`<div class="bar-wrap"><span class="bar-value">${v}</span><div class="bar" style="height:${Math.max(3,v/max*130)}px"></div><span class="bar-label">${k}</span></div>`).join('');const recent=[...data].slice(-5).reverse();$('#recent').innerHTML=recent.length?recent.map(x=>`<div class="recent-item"><div><div class="recent-name">${esc(x.student)}</div><div class="recent-meta">${esc(x.className)} · ${x.date}</div></div><span class="pill pill-${x.status.toLowerCase()}">${x.status}</span></div>`).join(''):'<p class="empty">Belum ada data absensi.</p>'}
function renderStudents(){if(!$('#studentRows'))return;const body=$('#studentRows');body.innerHTML='';$('#studentEmpty').style.display=students.length?'none':'block';students.forEach((x,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${esc(x.nis)}</td><td>${esc(x.name)}</td><td>${esc(x.className)}</td><td><button class="del" onclick="removeStudent(${i})">Hapus</button></td>`;body.appendChild(tr)});$('#studentCount').textContent=`${students.length} siswa`}
function populateLists(){if(!$('#studentOptions'))return;$('#studentOptions').innerHTML=students.map(x=>`<option value="${esc(x.name)}">${esc(x.className)}</option>`).join('');const classes=[...new Set(students.map(x=>x.className).filter(Boolean))];$('#classOptions').innerHTML=classes.map(x=>`<option value="${esc(x)}"></option>`).join('')}
function showPage(page){if(role!=='guru'&&['absensi','siswa'].includes(page))page='dashboard';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$('#'+page).classList.add('active-page');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#navlinks').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(page==='rekap')render()}
function applyRole(){document.querySelectorAll('.teacher-only').forEach(x=>x.style.display=role==='guru'?'':'none');$('#userBadge').textContent=role==='guru'?'👨‍🏫 Guru':'🎓 Siswa';$('#welcomeText').textContent=role==='guru'?'Kelola data siswa dan kehadiran dengan cepat.':'Selamat datang. Lihat rekap kehadiran yang tersedia.';showPage('dashboard');render()}
function login(){const u=$('#loginUser').value.trim().toLowerCase(),p=$('#loginPass').value;const valid=(role==='guru'&&u==='guru'&&p==='guru123')||(role==='siswa'&&u==='siswa'&&p==='siswa123');if(!valid){$('#loginError').textContent=role==='guru'?'Username/password guru salah.':'Username/password siswa salah.';return false}sessionStorage.setItem(sessionKey,role);$('#loginError').textContent='';$('#loginScreen').classList.add('hidden');applyRole();return true}
function logout(){sessionStorage.removeItem(sessionKey);role='guru';document.querySelectorAll('.role-tab').forEach(x=>x.classList.toggle('active',x.dataset.role==='guru'));$('#loginScreen').classList.remove('hidden');$('#loginUser').value='';$('#loginPass').value='';$('#loginError').textContent='';}
document.querySelectorAll('.role-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');role=b.dataset.role;$('#loginUser').value='';$('#loginPass').value='';$('#loginError').textContent='';$('#loginUser').focus()}));
$('#loginBtn').addEventListener('click',e=>{e.preventDefault();login()});
$('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login()}});
$('#loginUser').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#loginPass').focus()}});
$('#togglePass').addEventListener('click',()=>$('#loginPass').type=$('#loginPass').type==='password'?'text':'password');$('#logoutBtn').addEventListener('click',logout);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('#menuBtn').addEventListener('click',()=>$('#navlinks').classList.toggle('open'));
$('#add').addEventListener('click',()=>{if(!student.value.trim()||!className.value.trim()||!date.value)return alert('Isi tanggal, nama siswa, dan kelas terlebih dahulu.');data.push({student:student.value.trim(),className:className.value.trim(),date:date.value,status:status.value});student.value='';persist();showPage('dashboard')});
window.removeItem=i=>{if(role!=='guru')return;if(confirm('Hapus data ini?')){data.splice(i,1);persist()}};$('#clear').addEventListener('click',()=>{if(role!=='guru')return;if(confirm('Hapus seluruh data absensi?')){data=[];persist()}});
$('#addStudent').addEventListener('click',()=>{const nis=$('#studentNis').value.trim(),name=$('#studentName').value.trim(),cls=$('#studentClass').value.trim();if(!nis||!name||!cls)return alert('Isi NIS, nama, dan kelas.');if(students.some(x=>x.nis===nis))return alert('NIS sudah terdaftar.');students.push({nis,name,className:cls});$('#studentNis').value='';$('#studentName').value='';$('#studentClass').value='';persist();alert('Siswa berhasil ditambahkan.')});window.removeStudent=i=>{if(role!=='guru')return;if(confirm('Hapus siswa ini dari daftar?')){students.splice(i,1);persist()}};
[filterDate,filterClass,filterStatus].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));
$('#export').addEventListener('click',()=>{const filtered=filteredData();if(!filtered.length)return alert('Tidak ada data sesuai filter.');if(!window.jspdf)return alert('Modul PDF belum siap. Coba beberapa detik lagi.');const {jsPDF}=window.jspdf;const sekolah=schoolName.value.trim()||'Nama Sekolah',guru=teacherName.value.trim()||'Nama Guru',kelas=filterClass.value.trim()||'Semua Kelas',tanggal=filterDate.value?new Date(filterDate.value+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'}):'Semua Tanggal';const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(16);doc.text(sekolah,148,12,{align:'center'});doc.setFontSize(13);doc.text('REKAP ABSENSI SISWA',148,19,{align:'center'});doc.setFontSize(10);doc.text(`Kelas: ${kelas} | Tanggal: ${tanggal}`,148,26,{align:'center'});const counts={Hadir:0,Izin:0,Sakit:0,Alpa:0};filtered.forEach(x=>counts[x.status]++);doc.autoTable({startY:32,head:[['No','Nama Siswa','Kelas','Tanggal','Status']],body:filtered.map((x,i)=>[i+1,x.student,x.className,new Date(x.date+'T00:00:00').toLocaleDateString('id-ID'),x.status]),styles:{fontSize:9,cellPadding:3},headStyles:{fontStyle:'bold'},margin:{left:12,right:12}});let y=doc.lastAutoTable.finalY+8;doc.text(`Jumlah: Hadir ${counts.Hadir} | Izin ${counts.Izin} | Sakit ${counts.Sakit} | Alpa ${counts.Alpa}`,12,y);doc.text(`Dicetak: ${new Date().toLocaleString('id-ID')}`,12,y+6);doc.text('Mengetahui,',225,y+8,{align:'center'});doc.text('Guru / Wali Kelas',225,y+14,{align:'center'});doc.text(guru,225,y+34,{align:'center'});doc.line(190,y+36,260,y+36);doc.save(`rekap-absensi-${kelas.replace(/\s+/g,'-')}-${filterDate.value||'semua-tanggal'}.pdf`)});
schoolName.addEventListener('change',persist);teacherName.addEventListener('change',persist);date.value=new Date().toISOString().slice(0,10);schoolName.value=localStorage.getItem('school_name')||'';teacherName.value=localStorage.getItem('teacher_name')||'';$('#todayLabel').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
// Always require a fresh login when the site is opened; do not auto-enter the dashboard.
role='guru';sessionStorage.removeItem(sessionKey);$('#loginScreen').classList.remove('hidden');$('#loginUser').value='';$('#loginPass').value='';$('#loginError').textContent='';document.querySelectorAll('.role-tab').forEach(x=>x.classList.toggle('active',x.dataset.role==='guru'));applyRole();renderStudents();populateLists();
